// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinalAssignmentBE.Migrations
{
    [DbContext(typeof(FinalAssignmentDbContext))]
    [Migration("20250212231222_update nullable fields in game model")]
    partial class updatenullablefieldsingamemodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinalAssignmentBE.Models.Game", b =>
                {
                    b.Property<long>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GameId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberRange")
                        .HasColumnType("integer");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("integer");

                    b.HasKey("GameId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FinalAssignmentBE.Models.GameAttempt", b =>
                {
                    b.Property<long>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AttemptId"));

                    b.Property<long>("AttemptByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AttemptedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("AttemptId");

                    b.HasIndex("AttemptByUserId");

                    b.HasIndex("GameId");

                    b.ToTable("GameAttempts");
                });

            modelBuilder.Entity("FinalAssignmentBE.Models.GameQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GameAttemptId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCorrectAnswer")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameAttemptId");

                    b.ToTable("GameQuestions");
                });

            modelBuilder.Entity("FinalAssignmentBE.Models.GameRule", b =>
                {
                    b.Property<long>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RuleId"));

                    b.Property<int>("DivisibleNumber")
                        .HasColumnType("integer");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReplacedWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RuleId");

                    b.HasIndex("GameId");

                    b.ToTable("GameRules");
                });

            modelBuilder.Entity("FinalAssignmentBE.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinalAssignmentBE.Models.Game", b =>
                {
                    b.HasOne("FinalAssignmentBE.Models.User", "User")
                        .WithMany("Games")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalAssignmentBE.Models.GameAttempt", b =>
                {
                    b.HasOne("FinalAssignmentBE.Models.User", "AttemptByUser")
                        .WithMany()
                        .HasForeignKey("AttemptByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalAssignmentBE.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttemptByUser");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("FinalAssignmentBE.Models.GameQuestion", b =>
                {
                    b.HasOne("FinalAssignmentBE.Models.GameAttempt", "GameAttempt")
                        .WithMany("GameQuestions")
                        .HasForeignKey("GameAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameAttempt");
                });

            modelBuilder.Entity("FinalAssignmentBE.Models.GameRule", b =>
                {
                    b.HasOne("FinalAssignmentBE.Models.Game", "Game")
                        .WithMany("GameRules")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("FinalAssignmentBE.Models.Game", b =>
                {
                    b.Navigation("GameRules");
                });

            modelBuilder.Entity("FinalAssignmentBE.Models.GameAttempt", b =>
                {
                    b.Navigation("GameQuestions");
                });

            modelBuilder.Entity("FinalAssignmentBE.Models.User", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
