version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: FinalBE
      POSTGRES_PASSWORD: doxle
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: finalassignmentbe
    build:
      context: ./backend
      dockerfile: FinalAssignmentBE/Dockerfile
      target: final
    ports:
      - "4444:4444"
    environment:
      - FrontendUrl=http://localhost:3000,http://frontend:3000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=FinalBE;Username=postgres;Password=doxle
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://backend:4444
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://backend:4444
    depends_on:
      - backend

volumes:
  db-data:
